---
- name: A playbook to enable BITS and Spooler services
  hosts: 10.0.0.10
  tasks:
    - name: Enable Spooler
      win_service:
        name: spooler
        state: started
    - name: Enable BITS
      win_service:
        name: bits
        state: started