---
- name: A playbook to enable BITS and Spooler services
  hosts: dc00.lab.ferosfer.io
  tasks:
    - name: Enable Spooler
      win_service:
        name: spooler
        state: started
    - name: Enable BITS
      win_service:
        name: bits
        state: started